# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-18 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20190619_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostuser',
            name='auth_type',
            field=models.SmallIntegerField(choices=[('0', 'ssh-password'), ('1', 'ssh-key')], default='0'),
        ),
    ]
