# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-19 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20190619_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostgroup',
            old_name='binds_hosts',
            new_name='bind_hosts',
        ),
    ]
